name: Build Example (WASI)

on:
  push:
    branches: [main]
    paths:
      - "**.swift"
      - "**.yml"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ["swift:6.1"]

    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: swiftwasm/setup-swiftwasm@v2

      - name: Build
        working-directory: Examples/Basic
        run: ./build-wasi.sh
